apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: router
    app.kubernetes.io/name: alertmanager-main
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: v0.21.0
  name: alertmanager
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      alertmanager: main
      app.kubernetes.io/component: router
      app.kubernetes.io/name: alertmanager-main
      app.kubernetes.io/part-of: kube-prometheus
